### ISSUE TITLE
V1 compilation seems to assume popcount since version 0.4.0?

### ISSUE THREAD

**Issue by rwbc** [JacquesRW/akimbo#103]
Hi Jamie,

I am bit late for reporting ;) but I thought I let you know that I had to compile Akimbo myself
for my old hardware since the 0.4.0 release, while V1 still worked in 0.3.0.

As my current hardware from early 2009 (!) supports just SSE2, SSE3, SSSE3 and SSE4.1 but not popcount, I suspect
that the later releases somehow all are compiled with it. I guess this is not intended for V1 as it defeats
the purpose it. May be you can check again?

Best regards,
Guenther (RWBC XB/UCI chronology)

**Comment by JacquesRW** [comment]
Thanks for raising the issue @rwbc, I accidentally miscompiled them.

I have updated the V1 binaries in 0.4.0, 0.4.1 and 0.5.0, if you could possibly test one of them?

**Comment by rwbc** [comment]
I tested all three concerned compilations and now all of them are working!

Thank you for the quick reaction.

P.S. It would be nice, if you would support 'go depth' or 'go infinite' in the future.
(for now I used mostly 'go wtime X' for speed comparison.)

**Comment by JacquesRW** [comment]
I'll add `go depth` in the next release :)
